@echo off
echo ========================================
echo Enhanced React Native Version Mismatch Fix
echo ========================================
echo.

echo Step 1: Stopping any running Metro processes...
taskkill /f /im node.exe 2>nul || echo No Node processes found
taskkill /f /im expo.exe 2>nul || echo No Expo processes found

echo.
echo Step 2: Clearing npm cache completely...
npm cache clean --force
npm cache verify

echo.
echo Step 3: Clearing Expo cache and temp files...
npx expo r -c
rmdir /s /q %USERPROFILE%\.expo 2>nul || echo Expo cache not found, skipping...
rmdir /s /q %TEMP%\expo-* 2>nul || echo Expo temp files not found, skipping...

echo.
echo Step 4: Clearing Watchman cache (if available)...
watchman watch-del-all 2>nul || echo Watchman not available, skipping...

echo.
echo Step 5: Removing build artifacts and caches...
rmdir /s /q node_modules 2>nul || echo node_modules not found, skipping...
rmdir /s /q .expo 2>nul || echo .expo not found, skipping...
rmdir /s /q android\app\build 2>nul || echo Android build not found, skipping...
rmdir /s /q ios\build 2>nul || echo iOS build not found, skipping...
del package-lock.json 2>nul || echo package-lock.json not found, skipping...
del yarn.lock 2>nul || echo yarn.lock not found, skipping...

echo.
echo Step 6: Clearing Metro bundler cache...
npx @react-native-community/cli clean 2>nul || echo React Native CLI clean not available, skipping...
rmdir /s /q %TEMP%\metro-* 2>nul || echo Metro temp files not found, skipping...
rmdir /s /q %TEMP%\react-* 2>nul || echo React temp files not found, skipping...

echo.
echo Step 7: Reinstalling dependencies with clean slate...
npm install --no-cache

echo.
echo Step 8: Running Expo prebuild to regenerate native code...
npx expo prebuild --clean --clear-cache

echo.
echo Step 9: Resetting iOS Simulator (if available)...
xcrun simctl shutdown all 2>nul || echo iOS Simulator reset not available on Windows, skipping...

echo.
echo Step 10: Final verification...
echo Checking React Native version alignment...
npx react-native --version 2>nul || echo React Native CLI not available, skipping version check...

echo.
echo ========================================
echo Enhanced version mismatch fix complete!
echo ========================================
echo.
echo Next steps:
echo 1. Try running: npx expo start --clear
echo 2. If issues persist, restart your development machine
echo 3. Check that all caches have been cleared
echo.
pause
