-- Fix Recurring Tournament Issue
-- These tournaments keep persisting because they're part of a recurring series
-- that's being regenerated by the archival function

-- Step 1: Check if these are recurring tournaments
SELECT 
    id,
    id_unique_number,
    tournament_name,
    start_date,
    is_recurring,
    recurring_series_id,
    is_recurring_master
FROM tournaments
WHERE id_unique_number IN (19, 20);

-- Step 2: If they ARE recurring tournaments, we need to:
-- Option A: Delete the entire recurring series (if you don't want this tournament anymore)
-- Option B: Update the archival function to not regenerate past tournaments

-- OPTION A: Delete entire recurring series (RECOMMENDED if tournament is outdated)
-- First, find the recurring_series_id
DO $$
DECLARE
    series_id TEXT;
BEGIN
    -- Get the recurring series ID from one of the tournaments
    SELECT recurring_series_id INTO series_id
    FROM tournaments
    WHERE id_unique_number IN (19, 20)
    LIMIT 1;
    
    IF series_id IS NOT NULL THEN
        RAISE NOTICE 'Found recurring series: %', series_id;
        
        -- Delete ALL tournaments in this series (both active and future)
        DELETE FROM tournaments
        WHERE recurring_series_id = series_id;
        
        RAISE NOTICE 'Deleted all tournaments in series: %', series_id;
    ELSE
        RAISE NOTICE 'These are NOT recurring tournaments - safe to delete individually';
        
        -- Just delete these specific tournaments
        DELETE FROM tournaments
        WHERE id_unique_number IN (19, 20);
        
        RAISE NOTICE 'Deleted tournaments 19 and 20';
    END IF;
END $$;

-- Step 3: Verify deletion
SELECT 
    COUNT(*) as remaining_tournaments,
    'Should be 0 if series was deleted' as note
FROM tournaments
WHERE tournament_name LIKE '%metro chip%';

-- Step 4: Show what's left
SELECT 
    id_unique_number,
    tournament_name,
    start_date,
    status,
    is_recurring,
    recurring_series_id
FROM tournaments
WHERE status = 'active'
ORDER BY start_date;
