-- ============================================================================
-- FIX: Single Entry Giveaway Function
-- ============================================================================
-- This script:
-- 1. Drops all existing versions of fn_enter_giveaway to avoid conflicts
-- 2. Creates a single, comprehensive version that:
--    - Accepts all required parameters including full_name and birthday
--    - Checks the giveaway's single_entry setting
--    - Prevents duplicate entries when single_entry is enabled
--    - Stores all agreement data properly
-- ============================================================================

-- Drop all existing versions of the function to avoid conflicts
DROP FUNCTION IF EXISTS fn_enter_giveaway(UUID, BOOLEAN, BOOLEAN, BOOLEAN, BOOLEAN, BOOLEAN);
DROP FUNCTION IF EXISTS fn_enter_giveaway(UUID, BOOLEAN, BOOLEAN, BOOLEAN, BOOLEAN, BOOLEAN, VARCHAR, DATE);
DROP FUNCTION IF EXISTS fn_enter_giveaway(UUID);

-- Create the comprehensive function with all parameters
CREATE OR REPLACE FUNCTION fn_enter_giveaway(
  p_giveaway_id UUID,
  p_agree_18 BOOLEAN DEFAULT FALSE,
  p_agree_rules BOOLEAN DEFAULT FALSE,
  p_agree_privacy BOOLEAN DEFAULT FALSE,
  p_agree_one_entry BOOLEAN DEFAULT FALSE,
  p_marketing_opt_in BOOLEAN DEFAULT FALSE,
  p_full_name VARCHAR DEFAULT NULL,
  p_birthday DATE DEFAULT NULL
)
RETURNS JSON AS $$
DECLARE
  v_user_id UUID;
  v_existing_entry BIGINT;
  v_max_entries INT;
  v_current_entries BIGINT;
  v_single_entry BOOLEAN;
  v_giveaway_status TEXT;
BEGIN
  -- Get the authenticated user ID
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN json_build_object('success', false, 'message', 'User not authenticated');
  END IF;

  -- Get giveaway settings
  SELECT 
    maximum_entries, 
    single_entry,
    status
  INTO 
    v_max_entries, 
    v_single_entry,
    v_giveaway_status
  FROM giveaways
  WHERE id = p_giveaway_id;

  -- Check if giveaway exists
  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'message', 'Giveaway not found');
  END IF;

  -- Check if giveaway is active
  IF v_giveaway_status != 'active' THEN
    RETURN json_build_object('success', false, 'message', 'Giveaway is not active');
  END IF;

  -- Check for existing entry (always check, regardless of single_entry setting)
  SELECT COUNT(*) INTO v_existing_entry
  FROM giveaway_entries
  WHERE giveaway_id = p_giveaway_id AND user_id = v_user_id;

  -- If single_entry is enabled OR user already has an entry, prevent duplicate
  IF v_existing_entry > 0 THEN
    IF v_single_entry THEN
      RETURN json_build_object(
        'success', false, 
        'message', 'This giveaway allows only one entry per person. You have already entered.'
      );
    ELSE
      RETURN json_build_object(
        'success', false, 
        'message', 'You have already entered this giveaway'
      );
    END IF;
  END IF;

  -- Check if giveaway has reached maximum entries
  IF v_max_entries IS NOT NULL THEN
    SELECT COUNT(*) INTO v_current_entries
    FROM giveaway_entries
    WHERE giveaway_id = p_giveaway_id;

    IF v_current_entries >= v_max_entries THEN
      RETURN json_build_object('success', false, 'message', 'Giveaway has reached maximum entries');
    END IF;
  END IF;

  -- Validate required fields
  IF p_full_name IS NULL OR TRIM(p_full_name) = '' THEN
    RETURN json_build_object('success', false, 'message', 'Full name is required');
  END IF;

  IF p_birthday IS NULL THEN
    RETURN json_build_object('success', false, 'message', 'Birthday is required');
  END IF;

  -- Insert the entry (created_at is auto-generated by the database)
  INSERT INTO giveaway_entries (
    giveaway_id,
    user_id,
    agree_18,
    agree_rules,
    agree_privacy,
    agree_one_entry,
    marketing_opt_in,
    full_name,
    birthday
  ) VALUES (
    p_giveaway_id,
    v_user_id,
    p_agree_18,
    p_agree_rules,
    p_agree_privacy,
    p_agree_one_entry,
    p_marketing_opt_in,
    p_full_name,
    p_birthday
  );

  RETURN json_build_object(
    'success', true, 
    'message', 'Successfully entered the giveaway!'
  );
  
EXCEPTION
  WHEN OTHERS THEN
    RETURN json_build_object(
      'success', false, 
      'message', 'An error occurred: ' || SQLERRM
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Add comment to document the function
COMMENT ON FUNCTION fn_enter_giveaway IS 'Handles giveaway entry with single_entry enforcement, validation, and all agreement tracking';

-- Verification query
DO $$
BEGIN
  RAISE NOTICE '✅ fn_enter_giveaway function has been recreated successfully';
  RAISE NOTICE 'Function now supports:';
  RAISE NOTICE '  - Single entry enforcement based on giveaway.single_entry setting';
  RAISE NOTICE '  - Full name and birthday collection';
  RAISE NOTICE '  - All agreement tracking';
  RAISE NOTICE '  - Maximum entries validation';
  RAISE NOTICE '  - Giveaway status validation';
END $$;
